### ISSUE TITLE
v1.0.0 Release Checklist

### ISSUE THREAD

**Issue by integrii** [Comcast/kuberhealthy#93]
- [X] Update install instructions in issue #84 
- [X] Merge unstable into master
- [X] Add a `v1.0.0` tag to quay.io
- [X] Update helm chart to new release image
- [X] Merge master into the gh-pages branch to update the readme
- [X] Tag a v1.0.0 release on github

**Comment by integrii** [comment]
`quay.io/comcast/kuberhealthy:v1.0.0`

**Comment by integrii** [comment]
Builds are currently broken due to upstream changes. Before we can tag, we should do #40

**Comment by integrii** [comment]
https://github.com/helm/charts/pull/11341

**Comment by integrii** [comment]
https://github.com/Comcast/kuberhealthy/releases/tag/v1.0.0
